"""Score Explanation data structures.

REQ-008 §8.1: Explanation Components.

This module defines the data structures for human-readable score explanations
generated by the Strategist agent (see REQ-007 §7.6).

The ScoreExplanation dataclass provides a structured format for explaining
why a job received particular Fit and Stretch scores, including:
- What matches well (strengths)
- What's missing (gaps)
- Career growth potential (stretch opportunities)
- Concerns to be aware of (warnings)
"""

from dataclasses import dataclass


@dataclass(frozen=True)
class ScoreExplanation:
    """Human-readable explanation of job-persona match scores.

    REQ-008 §8.1: Explanation Components.

    Generated by the Strategist agent to explain why a job received
    particular Fit and Stretch scores. Provides actionable context
    for users reviewing job matches.

    Attributes:
        summary: 2-3 sentence overview of the match quality.
        strengths: What matches well between persona and job requirements.
        gaps: What's missing or where the user is underqualified.
        stretch_opportunities: Growth potential and career development value.
        warnings: Concerns like undisclosed salary, ghost risk, overqualified.

    Example:
        >>> explanation = ScoreExplanation(
        ...     summary="Strong technical fit with minor experience gap.",
        ...     strengths=["5/6 required skills", "Role title match"],
        ...     gaps=["Kubernetes experience required"],
        ...     stretch_opportunities=["ML pipeline exposure"],
        ...     warnings=["Salary not disclosed"],
        ... )
    """

    summary: str
    strengths: list[str]
    gaps: list[str]
    stretch_opportunities: list[str]
    warnings: list[str]
